CREATE TABLE products(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    state VARCHAR(100) NOT NULL,
    cover VARCHAR(100)  NULL,
    imgs VARCHAR(700) NULL,
     category VARCHAR(30) NOT NULL,
     model VARCHAR(100) NOT NULL,
     mark VARCHAR(100) NOT NULL,
     price DECIMAL(10, 2) NOT NULL,  
    about VARCHAR(500) NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  
);